-- MySQL Script generated by MySQL Workbench
-- Thu May  5 15:51:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sparta_realDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sparta_realDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sparta_realDB` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema sparta_realDB2
-- -----------------------------------------------------
USE `sparta_realDB` ;

-- -----------------------------------------------------
-- Table `sparta_realDB`.`waitingUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sparta_realDB`.`waitingUser` ;

CREATE TABLE IF NOT EXISTS `sparta_realDB`.`waitingUser` (
  `waitId` INT NOT NULL AUTO_INCREMENT,
  `Post_postId` INT NOT NULL,
  `createdAt` DATETIME NULL DEFAULT now(),
  `User_userId` INT NOT NULL,
  `User_userEmail` VARCHAR(200) NOT NULL,
  `User_userName` VARCHAR(45) NOT NULL,
  `User_userImage` VARCHAR(5000) NOT NULL,
  PRIMARY KEY (`waitId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
